In [1]:
import pandas as pd

In [50]:
df = pd.read_csv('../../2_Feature_Engineering/export/randomized_balanced_dataset.csv')
df

raw_text  severity  \
0     Ich warte schon darauf, dass man die Terrorist...       0.0   
1     Holt Björn Höcke ins Boot vielleicht haben wir...       0.0   
2     Deutscher, turkmenischer Abstammung bitte. Was...       0.0   
3     Wer glaubt die gehen wieder , ist einfach nur ...       0.0   
4     Man wünscht sich eine schlagkräftige Bürgerweh...       0.0   
5     er hat vollkommen recht  (aber ich wette, frau...       0.0   
6     Die echten Männer kämpfen gegen den Terror im ...       0.0   
7     Der Blade mit der Schrotflinte is lustig, abdr...       0.0   
8     Mein Gott das geht nicht anders! Ca. sechzig M...       0.0   
9     In Deutschlandradio Kultur erfahren wir gerade...       0.0   
10    Die EU-Kommission will die Verhandlungen über ...       0.0   
11                Habt ihr alle lust mit ein zu blasen?       0.0   
12     Warum gründet ihr denn auf VK keine 2. Comunity?       0.0   
13    Alle #Fluechtlinge nach #GG illegal!Nach Art. ...       0.0   
14                          das ist einfach unglaublich       0.0   
15    Was nützen Beschlüsse, wenn die Staaten die St...       0.0   
16    Oh mein Gott. CDU fordert von der Polizei, sie...       0.0   
17                             Lügen ,Lügen,über Lügen.       0.0   
18            Da kann einen schon der Brechreiz kommen.       0.0   
19    keine gnade , wer sowas macht raus aus deutsch...       0.0   
20    Gleiches recht für aller! jeder sollte ab heut...       0.0   
21       Ach nee...hört die propagandasender Merkels !!       0.0   
22                 und warum kommst nicht nach vk.com ?       0.0   
23                                              geteilt       0.0   
24    Vielleicht sollte man noch mehr spenden noch m...       0.0   
25    Die alte Frau brauch lange, um das zu vergesse...       0.0   
26      Ist ja gar nicht so verkehrt diese Frau Le Pen?       0.0   
27    Dann werden wir mal deren seite melden. Was di...       0.0   
28    So Fühl ich mich seit langem...Unter anderem i...       0.0   
29    genau diese 3 Begriffe hat Merkel vergewaltigt...       0.0   
...                                                 ...       ...   
1798  Seit gestern kann weder Die Bundes Regierung v...       1.0   
1799  #Europa ist groß, weil es nie islamisch war. U...       0.5   
1800  N24: Mehr Polizei, weniger Feiernde aber mehr ...       0.5   
1801  Langsam merken die Pfeifen, dass ihnen keiner ...       0.5   
1802  Ja genau.. Damit sie besser darauf stehen könn...       0.5   
1803                            VRBRENNEN diese WICHSER       1.0   
1804  0487530cd0db9917 Nicht nur Die ANTIFA Lappen s...       0.5   
1805                         schade das er es überlebte       1.0   
1806  Der einzige der anscheinend nicht die Augen ve...       0.5   
1807  Wie jeder mittlerweile weiß ist das was unser ...       0.5   
1808                 Sind und bleiben Dreckschweine..??       1.0   
1809  Frau Merkel wie konnen Sie mit ihre Gewissen l...       0.5   
1810  es soll ein IDIOTENTEST fur Politiker geben,we...       1.0   
1811  Dieser Deutsche Regierungssauhaufen macht mich...       1.0   
1812  Also das ist jetzt echt der Gipfel des eisberg...       1.0   
1813                                Schwanz ab - fertig       1.0   
1814  Bosbach allen Ehren aber solang er unter falsc...       0.5   
1815                             Zu dumm, zum Kacken :D       0.5   
1816                                  raus mit dem Pack       0.5   
1817  DDR war dagegen Gold wert. Da waren um dich he...       1.0   
1818  Es wird langsam mal Zeit, dass etwas passiert....       0.5   
1819  Das ist das Wahre Bild der Flüchtlinge!!! Mein...       1.0   
1820  Kein Sturm in Sicht,der rechtfertigt Umzüge an...       0.5   
1821                          L Ü G E N P R E S S E !!!       0.5   
1822  So ein wichser ! Sorry für den ausdruck ❗️ dan...       1.0   
1823                                     scheiss gsindl       1.0   
1824  Das ist die tolle Diktatur unserer Regi

# Clean text

In [3]:
from model_helpers import clean_input as ci

In [1]:
df['cleaned_text'] = df['raw_text'].apply(ci)

NameError: name 'df' is not defined

In [5]:
df

raw_text  severity  \
0     Ich höre und lese immer, schnell weg mit ihr e...       0.0   
1     Werden denn diese ausländischen Sexualstraftät...       0.0   
2     Sie soll hell und farbenfroh sein, viel Grün e...       0.0   
3     Wir sind wehrlos einer Invasion ausgesetzt. Fe...       0.0   
4     Weihnachts geschenk für die Geschwister und Ve...       0.0   
5     Leben wir wirklich in der BRD ???, glaub eher ...       0.0   
6                                            Genau wenn       0.0   
7                               Wie recht der Mann hat!       0.0   
8     Das ist nur lächerlich und typisch Deutsche We...       0.0   
9     Die begreifen das schon, aber es ist halt für ...       0.0   
10    Genug ist genug, wir brauchen keine Teppichbrü...       0.0   
11    Lest es und fallt vom Glauben ab !!! --- “In w...       0.0   
12    39e77c977585aa43 alles gut ausgebildete Frauen...       0.0   
13    In einem muss ich Nathan Frey jedoch Recht geb...       0.0   
14                             Sowas muss aus dem Amt .       0.0   
15    ``Derzeit können wir Dank willkürlicher Facebo...       0.0   
16    Vielleicht sollte man eine Talkshow zwischen d...       0.0   
17    „80 Prozent der Flüchtlinge junge, kräftig geb...       0.0   
18    Es wird ja immer irrer...wenn die da oben auch...       0.0   
19    Ist doch Dumm .. Schwarz Afrikaner kennen das ...       0.0   
20    Und der Heiko Maas heult schon wieder rum als ...       0.0   
21    #merkel will 100.000e #asylanten nach spanien ...       0.0   
22                       Die hat es damals schon gewußt       0.0   
23                              Den kann ich verstehen!       0.0   
24    Hinterher können sie das Hotel abreißen, ist j...       0.0   
25    Und dann ist es nur ne frage der zeit, bis die...       0.0   
26    wir werden doch nur noch verarscht!! Hoffe der...       0.0   
27    Wenn Medien ihre Darstellungskunst dazu missbr...       0.0   
28    Vielleicht steigt Mercedes ja in die Raumfahrt...       0.0   
29    http://youtu.be/z2nfyKAhvzQ . Mit den Mörderfa...       0.0   
...                                                 ...       ...   
1798  Hofentlich wird  die  nicht  mehr  gewählt.abe...       0.5   
1799  #Schönborn ist eine Schande! Er huldigt Invaso...       0.5   
1800   Hahahhaah wer hat dem denn ins Hirn geschissen ?       1.0   
1801  #ORF #ZIB20 #Vergewaltigung durch irak.#Asylan...       0.5   
1802  Was lernen wir daraus? Stefan ist ein Vollidio...       1.0   
1803  Dann sieht man Mal, wie krank unsere Politiker...       1.0   
1804  Das stimmt. ...ein schönes Familienbild......d...       0.5   
1805                         Jede Mülltonne hat mehr IQ       0.5   
1806  Wie immer bei ARD und dem anderen Dreck, Gott ...       1.0   
1807                 Du hast doch einen an der Klatsche       0.5   
1808      Bleibt standhaft gegen\r\nDer Verbrecherbande       0.5   
1809  War nur eine Frage der Zeit bis die Stasi-F*tz...       1.0   
1810                               Verdammte Wanzen !!!       1.0   
1811  Die ist krank, und keiner von den anderen kran...       0.5   
1812  Den verfluchten #Rapefugees den Krieg erklären...       0.5   
1813  Sind die wirklich alle sooo extrem dumm und me...       0.5   
1814  Und solches PACK soll Integriert werden ? Na p...       0.5   
1815  Ganz einfach wenn keiner Steuern zahlt auch di...       0.5   
1816  diese pissnelken hätten erst gar nicht in unse...       1.0   
1817  Nach der neuesten Idee unserer irren Kanzlerin...       0.5   
1818  In den Nachrichten kommt gerade nichts anders,...       1.0   
1819  wer zu dumm zum Scheißen ist, sollte wieder na...       0.5   
1820  Die Gutmenschen sagen "Wir haben einen Fehler ...       1.0   
1821  Immer wenn man einen weißen Hai braucht ist ke...       0.5   
1822  Wie blöd muß man sein wenn man das jetzt erst ...       0.5   
1823  Die Tschechen sind NICHT Islam feindlich ! Die...       1.0   
1824  Ihr hurensöhne wegen euren Demos die ni

# Vectorize

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
tfidf_bigram = TfidfVectorizer(ngram_range=(2,2))
tfidf_simple = TfidfVectorizer()

In [8]:
X_features_bigram = tfidf_bigram.fit_transform(df['cleaned_text'])
X_features_bigram

<1828x17030 sparse matrix of type '<class 'numpy.float64'>'
	with 18953 stored elements in Compressed Sparse Row format>

In [9]:
X_features_simple = tfidf_simple.fit_transform(df['cleaned_text'])
X_features_simple

<1828x7850 sparse matrix of type '<class 'numpy.float64'>'
	with 20054 stored elements in Compressed Sparse Row format>

In [16]:
tfidf_trigrams = TfidfVectorizer(ngram_range=(3,3))
X_features_trigrams = tfidf_trigrams.fit_transform(df['cleaned_text'])
X_features_trigrams

<1828x16066 sparse matrix of type '<class 'numpy.float64'>'
	with 17253 stored elements in Compressed Sparse Row format>

# Train with K-Fold & Random Forest

In [10]:
from sklearn.model_selection import KFold, cross_val_score

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
rf = RandomForestClassifier()

In [13]:
k_fold = KFold(n_splits=5, shuffle=True)

In [14]:
# k-fold without n-grams
cross_val_score(rf, X_features_simple, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.72131148, 0.64754098, 0.65027322, 0.70136986, 0.62465753])

In [15]:
# k-fold with bigrams
cross_val_score(rf, X_features_bigram, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.53278689, 0.60655738, 0.57650273, 0.54794521, 0.58356164])

In [18]:
# k-fold with trigrams
cross_val_score(rf, X_features_trigrams, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.55464481, 0.56557377, 0.54371585, 0.52054795, 0.59452055])

# Train with K-Fold & Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
lr = LogisticRegression()

In [21]:
# logistic regression without n-grams
cross_val_score(lr, X_features_simple, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.70765027, 0.70765027, 0.71038251, 0.68767123, 0.75616438])

In [22]:
# k-fold with bigrams
cross_val_score(lr, X_features_bigram, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.56010929, 0.57650273, 0.56557377, 0.56438356, 0.57534247])

# Train with K-Fold & Gaussian Naive Bayes

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
nb = GaussianNB()

In [26]:
# NB without n-grams
cross_val_score(nb, X_features_simple.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.66393443, 0.66666667, 0.62021858, 0.67671233, 0.62465753])

In [27]:
# NB with bigrams
cross_val_score(nb, X_features_bigram.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.58469945, 0.59016393, 0.60382514, 0.5890411 , 0.60821918])

# Train with K-Fold & Multinomial Naive Bayes

In [28]:
from sklearn.naive_bayes import MultinomialNB

In [29]:
mnb = MultinomialNB()

In [30]:
# MNB without n-grams
cross_val_score(mnb, X_features_simple.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.68579235, 0.68306011, 0.73224044, 0.70684932, 0.72876712])

In [31]:
# MNB with bigrams
cross_val_score(nb, X_features_bigram.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.60655738, 0.56284153, 0.58469945, 0.57808219, 0.58630137])

# Train with K-Fold & support vector machine

In [32]:
from sklearn.linear_model import SGDClassifier

In [33]:
svm = SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42, max_iter=5, tol=None) # params only copied

In [37]:
# SVM without n-grams
cross_val_score(svm, X_features_simple.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.63661202, 0.64480874, 0.67759563, 0.6739726 , 0.7260274 ])

In [38]:
# SVM with bigrams
cross_val_score(svm, X_features_bigram.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

array([0.5136612 , 0.56557377, 0.53005464, 0.50410959, 0.54794521])

# results

seems as using n-grams would not improve the model. following the best from all algorithms

In [42]:
svm = cross_val_score(svm, X_features_simple.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)
mnb = cross_val_score(mnb, X_features_simple.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)
gnb = cross_val_score(nb, X_features_simple.toarray(), df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)
lr = cross_val_score(lr, X_features_simple, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)
rf = cross_val_score(rf, X_features_simple, df['binary_label'], cv=k_fold, scoring='accuracy', n_jobs=-1)

print('scores')
print('svm: {}'.format(svm))
print('mnb: {}'.format(mnb))
print('gnb: {}'.format(gnb))
print('lr: {}'.format(lr))
print('rf: {}'.format(rf))

scores
svm: [0.60382514 0.59289617 0.67759563 0.70410959 0.6630137 ]
mnb: [0.71311475 0.70491803 0.7295082  0.70958904 0.70136986]
gnb: [0.6284153  0.66939891 0.63387978 0.64383562 0.63287671]
lr: [0.71038251 0.69398907 0.74863388 0.70684932 0.68219178]
rf: [0.66939891 0.66120219 0.62295082 0.7260274  0.63561644]


In [46]:
print('score averages')
print('svm: {}'.format(sum(svm) / len(svm)))
print('mnb: {}'.format(sum(mnb) / len(mnb)))
print('gnb: {}'.format(sum(gnb) / len(gnb)))
print('lr: {}'.format(sum(lr) / len(lr)))
print('rf: {}'.format(sum(rf) / len(rf)))

score averages
svm: 0.6482880455123887
mnb: 0.7116999775432292
gnb: 0.6416812635676323
lr: 0.7084093120742571
rf: 0.6630391496369489


In [48]:
scores = {
    'svm': sum(svm) / len(svm),
    'mnb': sum(mnb) / len(mnb),
    'gnb': sum(gnb) / len(gnb),
    'lr': sum(lr) / len(lr),
    'rf': sum(rf) / len(rf)
}

for key, value in sorted(scores.items(), key=lambda item: item[1], reverse=True):
    print("%s: %s" % (key, value))

mnb: 0.7116999775432292
lr: 0.7084093120742571
rf: 0.6630391496369489
svm: 0.6482880455123887
gnb: 0.6416812635676323
